#Author: Stetson Baber
#Web Server Dockerfile
FROM debian
RUN set -e
RUN set -x

RUN mv /usr/sbin/policy-rc.d.disabled /usr/sbin/policy-rc.d

RUN apt-get update
RUN apt-get -y --no-install-recommends install less nano vim-tiny man-db \
        exim4-daemon-light bsd-mailx pwgen gnupg gnupg2 \
        netcat-openbsd socat openssl ssh telnet net-tools wget curl zip unzip unattended-upgrades needrestart debian-security-support apache2 certbot python-certbot-apache python-ndg-httpsclient ssl-cert \
             acme-tiny libapache2-mod-php 
RUN apt-get -y -u dist-upgrade
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/local/bin/docker-wipelogs

RUN mv /usr/sbin/policy-rc.d /usr/sbin/policy-rc.d.disabled
EXPOSE 80 CMD [“apache2ctl”, “-D”, “FOREGROUND”]